{
 "title": "Mirth Metrics Dashboard",
 "description": "Basic overview of host metrics and mirth metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hostname",
    "query": "label_values(windows_os_time{job=~\"$job\"},instance)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(windows_os_time, job)"
   },
   { "name": "interval", "query": "1h" },
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_success_timestamp_seconds"
    }
   ]
  },
  {
   "title": "Total Mirth Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((up{job=\"mirth\"}))"
    }
   ]
  },
  {
   "title": "Inactive Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((up{job=\"mirth\"})==0)"
    }
   ]
  },
  {
   "title": "Total Channels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_channels_deployed)"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_messages_received_total)"
    }
   ]
  },
  {
   "title": "Errored Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_messages_errored_total)"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (time) (mirth_messages_queued)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1.5, "w": 24, "x": 0, "y": 4 }, "content": "__Server Monitor__" },
  {
   "title": "Top 5 CPU Usages",
   "type": "table",
   "description": "Shows top 5 instances with maximum CPU utilization",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,sort_desc(avg by (instance) ((1 - (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) > 0)*100)))"
    }
   ]
  },
  {
   "title": "Top 5 Memory Usages",
   "type": "table",
   "description": "Shows top 5 instances with maximum memory utilization",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,sort_desc(avg by (instance) ((1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))*100)))"
    }
   ]
  },
  {
   "title": "Top 5 Disk Usages",
   "type": "table",
   "description": "Shows top 5 instances with maximum DIsk utilization",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) ((node_filesystem_size_bytes-node_filesystem_free_bytes) *100/(node_filesystem_avail_bytes +(node_filesystem_size_bytes-node_filesystem_free_bytes)))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1.5, "w": 24, "x": 0, "y": 12.5 }, "content": "__Interface Monitor__" },
  {
   "title": "Inactive Channels(Last 12hrs)",
   "type": "table-old",
   "description": "Shows inactive channels which have not  received messages from last 12hrs",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(ceil(avg_over_time(mirth_messages_received_total{job=\"mirth\"}[1m])-avg_over_time(mirth_messages_received_total{job=\"mirth\"}[12h])))<=0"
    }
   ]
  },
  {
   "title": "Top 5 Errored Channels(Last $interval)",
   "type": "table-old",
   "description": "Shows top 5 channels with errored messages received in last 1hr",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sort_desc(topk(5,((mirth_messages_errored_total-mirth_messages_errored_total offset 1h) OR (mirth_messages_errored_total-mirth_messages_errored_total offset 1m))>0))"
    }
   ]
  },
  {
   "title": "Top 5 Queued Channels",
   "type": "table-old",
   "description": "Shows top 5 channels with queued messages and channels with sent messages threshold drop(60%)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sort_desc(topk(5,(mirth_messages_queued>0) or ((mirth_messages_queued>0) and (((((mirth_messages_sent_total - mirth_messages_sent_total offset 12h)/(12*60))*0.6)-((mirth_messages_sent_total - mirth_messages_sent_total offset 15m)/(15)))>0))))  "
    }
   ]
  },
  {
   "title": "Throughput Monitor",
   "type": "graph",
   "description": "Total messages sent in last 1 minute",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mirth_messages_sent_total-mirth_messages_sent_total offset 1m)>=0"
    }
   ]
  }
 ]
}